name=UCOP
version=0.3.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Universal Communication Protocol (UCOP)
paragraph=Universal communication protocol (UCOP) for command and data exchange between microcontrollers and/or computers.
category=Communication
url=https://github.com/TobiasKnauss/ArduinoLib_UCOP
architectures=*
