X(FAIL_UCOP_Message_CommandIdInvalid        )
X(FAIL_UCOP_Message_MessageIdInvalid        )
X(FAIL_UCOP_Message_NotFound                )
X(FAIL_UCOP_Message_ReceiverDeviceIdMismatch)
X(FAIL_UCOP_Message_SenderDeviceIdInvalid   )
X(FAIL_UCOP_Message_ResultWrong             ) 
X(FAIL_UCOP_Message_TimestampInvalid        )
X(FAIL_UCOP_CalcChecksum                    )
